// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Toaster } from "sonner";
// import StoreProvider from "./StoreProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <StoreProvider>
//       <html lang="en">
//         <body className={`${inter.className} min-h-screen flex flex-col`}>
          
//           <Navbar />
//           {/* <SearchOptions/> */}
//           <div className="md:bg-[#F4F2EE] flex-1 w-full">
//             <main className="max-w-6xl mx-auto">
//               {children}
//               <Toaster position="top-right" />
//             </main>
//           </div>
//           {/* <MobileNavbar/> */}
//         </body>
//       </html>
//       </StoreProvider>
//     </ClerkProvider>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "./StoreProvider";
import MobileNavbar from "@/components/MobileNavBar";
import SearchOptions from "@/components/SearchOption";
import Navbar from "@/components/Navbar";
import { auth } from "@clerk/nextjs/server";
import { createUserIfNotExists } from "@/lib/serveractions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LinkedIn",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  if (userId) {
    await createUserIfNotExists();
  }
  return (
    <ClerkProvider signInUrl="/sign-in">
      <html lang="en">
        <body className={`min-h-screen flex flex-col ${inter.className}`}>
          <StoreProvider>
            <Navbar />
            <SearchOptions />
            <div className="md:bg-[#F4F2EE] flex-1 w-full">
              <main>
                {children}
                <Toaster position="top-right" />
              </main>
            </div>
            <MobileNavbar />
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

